---
- hosts: "{{host}}"
  become: true
  tasks:
  
  - name: Install packages
    yum:
      name: "{{item}}"
      state: present
    with_items:
      - java-1.8.0
      - tomcat
      - tomcat-webapps
      - tomcat-admin-webapps

  - name: copy tomcat user file to tomcat server
    copy:
      src: tomcat-users.xml
      dest: /etc/tomcat/tomcat-users.xml
      
           
  - name: Deploy Artifacts to tomcat server
    get_url: 
      url: http://100.20.122.10:8081/repository/GAME/Env/Env/1.1/Env-1.1.war
      url_username: admin
      password: 1234
      dest: /usr/share/tomcat/webapps/
  
  - name: restart tomcat server
    service:
      name: tomcat
      state: restarted
      
      
      
      

